Mvp
Hedge-for-Humanity/DollarForEveryone pull request #1
Opened 2020-11-26 20:14 UTC by DrewGregory

This is the basic beginning of the MVP for DollarForEveryone.

It includes:

- 2 screens overlayed over the Burner Wallet: the Splash screen with some explanatory text and a deep link button, NotVerified Screen which encourages the user that they have linked their BrightID but need to do some extra work to reach verified status. Once the user is linked and verified, they are automatically navigated to the burner wallet screen.
- Backend server code: This receives the autogenerated client address for the burner wallet, which will then return a deep link associated with the address,

2020-11-26 20:23 UTC, DrewGregory commented
This does *not* cover various aspects of the MVP including the feedback form and privacy policy.

2020-12-14 17:16 UTC, adamstallard commented on backend/server.js
> +    gasPrice: 100000000,
```suggestion
    gasPrice: 10000000000,
```

2020-12-15 01:18 UTC, adamstallard commented on backend/server.js
> +
```suggestion
```

It seems this function is no longer used now that we're using stable-json-stringify and nacl.sign to encode operations.

2020-12-15 01:22 UTC, adamstallard commented on backend/server.js
> +    chainID: 1337 // ganache chain id
We'll probably need a way to set the real chainID for IDChain (`0x4a` or `74`) and connect to an rpc node (https://idchain.one/rpc)  See "[add IDChain to metamask](https://brightid.gitbook.io/brightid/idchain/add-idchain-to-metamask)"

2020-12-15 01:26 UTC, adamstallard commented on basic-wallet/src/App.tsx
> +import Exchange, { Uniswap, XDaiBridge } from '@burner-wallet/exchange';
We may need to look at the xdai gateway, xdai bridge, and uniswap libraries and make sure we're using the idchain equivalents, e.g. https://uniswap.idchain.one https://dai.idchain.one

2020-12-15 01:28 UTC, adamstallard requested changes
The only substantial changes involve making sure that we're connecting to IDChain, not xdai chain.  Happy to help with this.

2022-10-02 22:58 UTC, closed without merging